name: Waka Readme

on:
  schedule:
    - cron: '00 23 * * *'
  push:
    branches:
      - main
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: PstasDev/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_HIREABLE: "False"
          SYMBOL_VERSION: 2
          DEBUG_LOGGING: "True"